### ISSUE TITLE
editor window not rendering 

### ISSUE THREAD

**Issue by bartart3d** [PiOverFour/MPK-M2-editor#12]
Hi ,
not sure what I've done wrong, but suddenly the editor won't launch anymore, no clue what is changed.
After Ctrl-C  I get the following traceback:

```
^CTraceback (most recent call last):'
  File "/home/bart/Documenten/software/audio/mpkmini/MPK-M2-editor-master/./mpk-m2-editor", line 376, in <module>
    ui.get_all_programmes()
  File "/home/bart/Documenten/software/audio/mpkmini/MPK-M2-editor-master/./mpk-m2-editor", line 291, in get_all_programmes
    self.get_programme(p_i)
  File "/home/bart/Documenten/software/audio/mpkmini/MPK-M2-editor-master/./mpk-m2-editor", line 300, in get_programme
    in_message = self.send_midi_message(out_message, 117)
  File "/home/bart/Documenten/software/audio/mpkmini/MPK-M2-editor-master/./mpk-m2-editor", line 283, in send_midi_message
    in_message = self.mi.get_message()
KeyboardInterrupt
```
I hope this helps to find a solution.

grtz,
Bart

**Comment by PiOverFour** [comment]
Hello @bartart3d, thanks for the report. I can't reproduce the issue right now but it looks to be a MIDI issue, the program probably can't communicate with the controller.
Have you changed your setup or updated something? Do you have multiple controllers or MIDI device? What OS do you use?

**Comment by bartart3d** [comment]
Sorry for the late reply, jobs and travels kept me away from here.

It's possible my setup has changed a bit, I mean, linux is being updated al the time, and software updates are happening quite often. I tried different cables, usb ports, but that all doesn't seem to work. 
I'm  running ubuntustudio 21.10. I had changed the midi channel in RAM to 3 in a previous session. It hangs in jack, 

If it's because of a change in the system, is there something like a settings file that needs to be reset, removed, or changed?

grtz,
Bart
