### ISSUE TITLE
Support for MPK mini mk3

### ISSUE THREAD

**Issue by ehanuise** [PiOverFour/MPK-M2-editor#8]
Hi.
I just purchased a MPK mini and got the newer MK3 model.
I tried installing the editor, and got a "device not found" error.

I tried adding "MPK mini" to the arrays in lines 252 and 255 as I noticed the mk3 has a lowercase mini in the name. 
       is_out_open, is_in_open = False, False
       for i, p in enumerate(self.mo.get_ports()):
           if any(mpk in p for mpk in ("MPKmini", "MPK Mini", "MPK mini")):
               self.mo.open_port(i)
               is_out_open = True
       for i, p in enumerate(self.mi.get_ports()):
           if any(mpk in p for mpk in ("MPKmini", "MPK Mini", "MPK mini")):
               self.mi.open_port(i)
               self.mi.ignore_types(sysex=False)
               is_in_open = True
If I unplug the keyboard, I get the 'device not found' message so that part at least I got right ^^

Now, once launched, the editor opens a window but that window stays empty. (It copies the screen and doesn't refresh or go black or anything. the window can be moved around and keeps the same image inside.) Resize works (fills the rest with black) but not the close window 'x' button.

When I eventually ctrl-c to kill it, the following message appears in the console : 

./mpk-m2-editor.py 
^CTraceback (most recent call last):
  File "./mpk-m2-editor.py", line 376, in <module>
    ui.get_all_programmes()
  File "./mpk-m2-editor.py", line 291, in get_all_programmes
    self.get_programme(p_i)
  File "./mpk-m2-editor.py", line 300, in get_programme
    in_message = self.send_midi_message(out_message, 117)
  File "./mpk-m2-editor.py", line 283, in send_midi_message
    in_message = self.mi.get_message()
KeyboardInterrupt

I am not a developper so my abilities to help solving this are limited, but I will gladly try to help getting the editor wirk with an mk3 :)
I'm using ubuntu 20.4

**Comment by PiOverFour** [comment]
Hello, thanks for the report.
Unfortunately, I expect the format used by Akai to exchange data is different. I tried looking around, but haven’t found any information on this device. Perhaps some hacker will get it and find out how it works! I don’t have this controller myself and cannot test it further…
In any case, the editor would need to be modified quite a lot to work with other models, and I still don’t really have the time to do that.
Sorry I can’t be more helpful for now :/

**Comment by ehanuise** [comment]
Well, no problem of course, it's the nature of open source, everyone contributes at their own pace :-)
Thanks anyways for taking the time to reply!

**Comment by ehanuise** [comment]
Hi again. This project has a working editor for the mk3 :-)
https://github.com/tsmetana/mpk3-settings 
sysex table is in https://github.com/tsmetana/mpk3-settings/blob/master/src/message.h :-)

**Comment by stefets** [comment]
@ehanuise have you tried this editor ? 

It state : It's in a very early stage of development and has not been thoroughly tested.
Use at your own risk.

I don't want to burn my controller !

**Comment by ehanuise** [comment]
No risk of burning it up, it only sends midi sysex ;-)
It works. I still have buyer's remorse and will favor novation gear for future purchases as their components web-tools works fine in Linux.

**Comment by stefets** [comment]
Ok! thanks; I am in the process of adding a controller to my setup; I will look at the Novation gear, the Lunchkey Mini looks fine!

**Comment by jmfergeau** [comment]
Je plussoie J'aimerais bien du support pour ce modèle là, aussi. Parce que là pour l'instant, le mien fait rien nulle part, il est juste visible avec lsusb :D

**Comment by ehanuise** [comment]
@maxlefou essayez https://github.com/tsmetana/mpk3-settings  ;-)

**Comment by davybjj** [comment]
Hello,
I would keep using the app for Adour which doesn't sync the tempo with the mpk, but my skills are maxed out, I downloaded the zip link in the Download folder.. I never compiled. I ran the commands in the terminal, had to install the commands

$ ./autogen.sh
$ ./config
$ do

Several folders have been added in the directory containing it.
but when running make I get a return asking me for an "I assume" installation path.
Maybe I have to do it from another place? in the root? which directory?
Maybe I'm missing packages for the compilation?
I am a little lost. I don't want to take too much of your time either.
do you have any advice or clarification?
thank you.

**Comment by PiOverFour** [comment]
@davybjj Hi, I’m not sure how you got these instructions, this program does not use AutoGen at all. Where did you get the zip file from?

**Comment by davybjj** [comment]
Hello, thank you for your response.
I'm off to a bad start. :-(
It's a translation novice error, I'm not an English speaker I translated
all the text sorry: the zip has been uploaded on the github:
https://github.com/tsmetana/mpk3-settings
The commands used are those at the bottom of the page.

$ autoreconf -i
$ ./configure
$ make

I had to install packages for the "configure" command, my system is
ubuntustudio 22.04, not equipped for compiled it seems to me? The "make"
step is the problem. A destination is requested, folder or parameters
command? i don't know, I looked at the parameters of this command but I do
not measure its scope, its use and its parameters. Or I may not have any
dependencies for compilation?
thank you


Le jeu. 13 oct. 2022 à 00:56, PiOverFour ***@***.***> a
écrit :

**Comment by PiOverFour** [comment]
@davybjj Ah I see. Well I’m not the developer of that program and I have no idea how it works unfortunately.
Maybe you’d have better luck [asking them directly](https://github.com/tsmetana/mpk3-settings/issues)?
Also when asking for support help, it would help to know what you are trying to do and what errors you get, so pasting a terminal output is generally useful.

🇫🇷 D’acc, je vois. En fait je ne suis pas le développeur de ce progamme et je ne sais pas du tout comment il marche.
Peut-être que tu ferais mieux de [leur demander directement](https://github.com/tsmetana/mpk3-settings/issues) ?
En général, si tu demandes de l’aide, c’est utile de savoir ce que tu essaies de faire et quelles erreurs tu eues, donc coller la sortie du terminal peut aider.

**Comment by davybjj** [comment]
Thank you for your help and advice, I was able to install the interface on
my own, I understand the GIT-hub a little better. I try to put sounds on
it, on the ardor 7 Have a nice day
Résultats de traduction
star_border
Thank you for your help and advice, I was able to install the interface on
my own, I understand the GIT-hub a little better. I try to put sounds on
it, on the ardor 7 Have a nice day

Le jeu. 13 oct. 2022 à 15:19, PiOverFour ***@***.***> a
écrit :
